name: Kubernetes-sigs/krew CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.17]
    steps:

    - name: Set up Go ${{ matrix.goVer }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.goVer }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install dependencies
      run: go mod download

    - name: Install gox
      run: hack/install-gox.sh

    - name: Make binaries && verify krew installation
      run: hack/make-all.sh

    - name: Create a new release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        files: out/krew*
        generate_release_notes: true
        apend_body: true
